##################
# All rules specific to this repo
##################

inherit_from: .rubocop_general.yml

# e.g. 
# def self.is_supported?(platform)
# we may never use `platform`
Lint/UnusedMethodArgument:
  Enabled: false

# the let(:key) { ... }
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'spec/**/*'

# We use `is_supported?` everywhere already
Style/PredicateName:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'lib/fastlane/actions/*.rb'
    - 'bin/fastlane'

AllCops:
  Exclude:
    - 'lib/assets/custom_action_template.rb'
