inherit_from: .rubocop_todo.yml

Style/ClassCheck:
  EnforcedStyle: kind_of?

# Offense count: 31
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BracesAroundHashParameters:
  Enabled: false

